title: Garrett Grimm - Web Developer &amp; Musician
description: >
  **Garrett Grimm**, Web Developer and Musician.
copyright: Garrett Grimm
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username: "grimmdude"
linkedin_username: "ggrimm"
instagram_username: "grimmdude"
pinterest_username:
flickr_username:
github_username:  "grimmdude"
feed_icon: rss
email:
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
